project:
  type: website
  output-dir: docs

website:
  title: ""
  google-analytics: "G-EG6MCCLWVL"
  cookie-consent: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Roboto"
    page-layout: full



