project:
  type: website
  output-dir: docs

website:
  title: "Resume"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Roboto"
    page-layout: full



