---
title: "Joel Barnes &#187; Data Scientist | Model Developer | Analytics"
---

<h1 class="roboto-black to-upper" style="font-size: 2.5em;">Joel Barnes</h1>

<h4 style="margin-top: -0.85em; padding-top: 0;" class="roboto-bold color-grey1">Data Scientist | Model Developer | Analytics</h4>

<p class="roboto-light">
  <span class="roboto-light color-blue">{{< fa envelope >}}</span> <a href="mailto:j@barnzilla.ca">j@barnzilla.ca</a>
  <span class="roboto-light color-blue" style="margin-left: 8px;">{{< fa phone >}}</span> (613) 408-6089
  <span class="roboto-light color-blue" style="margin-left: 8px;"><i class="fa-brands fa-github"></i></span> <a href="https://github.com/barnzilla" target="_blank">github.com/barnzilla</a>
  <span class="roboto-light color-blue" style="margin-left: 8px;"><i class="fa-brands fa-linkedin"></i></span> <a href="https://www.linkedin.com/in/joel-barnes-5a80a449" target="_blank">linkedin.com/in/joel-barnes-5a80a449</a>
  <span class="roboto-light color-blue" style="margin-left: 8px;">{{< fa location-dot >}}</span> Ottawa, Canada <i class="fa-brands fa-canadian-maple-leaf color-red"></i>
</p>

<h3 class="roboto-black to-upper" style="border-bottom: 2px solid black;">Experience</h3>

<h4 class="roboto-light color-grey1" style="margin-top: 0; margin-bottom: 0; padding-top: 0; font-size: 1em;">Data Scientist</h4>

<p class="roboto-light color-black" style="margin-bottom: 0;">
  <span class="roboto-bold">Statistics Canada</span>
  <br />
  <span class="roboto-light color-grey1">{{< fa calendar-days >}}</span> 
  2020 - present
  <span class="roboto-light color-grey1" style="margin-left: 8px;">{{< fa location-dot >}}</span>
  Ottawa, Canada
  <ul class="roboto-light color-black" style="margin-top: 0; padding-top: 0;">
    <li>Develop and maintain <a href="https://www.statcan.gc.ca/en/microsimulation/modgen/new/mods/pohem" target="_blank">POHEM</a> (a longitudinal microsimulation model that forecasts various health risk factors and outcomes &mdash; obesity, diabetes, dementia, cardiovascular disease &mdash; in Canadians from 2001 to 2050) that is used by the Government of Canada to inform policy decisions.</li>
    <li>Authored and maintain <strong>chms</strong> (an internal, object-oriented R package that applies sleep, physical activity and sedentary behavior algorithms to accelerometer-measured time series data) that a division with no open source expertise used to process accelerometer data on 4,000+ participants for cycle 7 of a nationally representative survey, the <a href="https://www23.statcan.gc.ca/imdb/p2SV.pl?Function=getSurvey&SDDS=5071" target="_blank">Canadian Health Measures Survey</a>.</li>
    <li>Authored and maintain <strong>ompp4aaw</strong> (an internal R package that allows users with little or no proficiency in Linux distributions and Kubernetes to install, compile and run their models) that is used by model developers across several microsimulation divisions.</li>
    <li>Authored and maintain <a href="https://613apps.ca/data-dictionary-builder" target="_blank">Data Dictionary Builder</a> (an R Shiny web-based app that groups survey metadata from flat files across multiple cycles of several national surveys and makes it searchable) that enables Statistics Canada analysts and external researchers to find variables and plan analyses more efficiently.</li>
    <li><a href="https://www.statcan.gc.ca/en/data-science/network/ppe-demand" target="_blank">Modeled Covid-19 cases in nine Canadian provinces</a> on a weekly basis during the Covid-19 pandemic using compartment models via a co-authored R package, <a href="https://github.com/statcan/episim" target="_blank">EpiSim</a>. Created scenarios that forecasted Covid-19 cases one year into the future. Results were used downstream in a Microsoft Azure pipeline to help the Government of Canada forecast personal protective equipment demand and make evidence-informed procurement decisions.</li>
  </ul>
</p>

<h4 class="roboto-light color-grey1" style="margin-bottom: 0; padding-top: 0; font-size: 1em;">Data Scientist</h4>

<p class="roboto-light color-black" style="margin-bottom: 0;">
  <span class="roboto-bold">CHEO Research Institute</span>
  <br />
  <span class="roboto-light color-grey1">{{< fa calendar-days >}}</span> 
  2008 - 2019
  <span class="roboto-light color-grey1" style="margin-left: 8px;">{{< fa location-dot >}}</span>
  Ottawa, Canada
  <ul class="roboto-light color-black" style="margin-top: 0; padding-top: 0;">
    <li>Performed various modeling techniques on large datasets related to movement behaviours (physical activity, sedentary behavior, sleep) and health outcomes in children and youth. Analyses have been published in <a href="https://scholar.google.com/citations?user=oIMGmrQAAAAJ&hl=en" target="_blank">70+ peer-reviewed publications</a> contributing to an h-index of <a href="https://scholar.google.com/citations?user=oIMGmrQAAAAJ&hl=en" target="_blank">40</a>, which is equivalent to the research output of a full professor.</li>
    <li>Served as a “full-stack” web developer that designed, built and maintained five websites on LAMP stacks: <a href="https://www.activehealthykids.org" target="_blank">activehealthykids.org</a>, <a href="https://web.archive.org/web/20220627075842/https://www.capl-eclp.ca" target="_blank">capl-eclp.ca</a>, <a href="https://www.haloresearch.ca" target="_blank">haloresearch.ca</a>, <a href="https://www.outdoorplaycanada.ca" target="_blank">outdoorplaycanada.ca</a>, <a href="https://www.sedentarybehaviour.org" target="_blank">sedentarybehaviour.org</a>. </li>
    <li>Served as lead author on seven <a href="https://www.participaction.com/the-science/children-and-youth-report-card" target="_blank">ParticipACTION Report Cards on Physical Activity for Children and Youth</a> (2011-2016, 2018), a knowledge translation product that <a href="https://journals.humankinetics.com/view/journals/jpah/11/s1/article-pS3.xml" target="_blank">has received one billion+ media impressions and that has an estimated collective ad value of $10 million+</a>.</li>
  </ul>
</p>

<h4 class="roboto-light color-grey1" style="margin-bottom: 0; padding-top: 0; font-size: 1em;">Freelance Web Developer</h4>

<p class="roboto-light color-black" style="margin-bottom: 0;">
  <span class="roboto-bold">Barnzilla Web Development</span>
  <br />
  <span class="roboto-light color-grey1">{{< fa calendar-days >}}</span> 
  2006 - present
  <span class="roboto-light color-grey1" style="margin-left: 8px;">{{< fa location-dot >}}</span>
  Ottawa, Canada
  <ul class="roboto-light color-black" style="margin-top: 0; padding-top: 0;">
    <li>Develop, design and maintain custom websites for clients on virtual private servers (LAMP stacks). Some of these clients are academic research networks where custom code is actively deployed to handle all aspects of conference management (e.g., abstract submission and review, membership and conference registration, fee processing).</li>
    <li>Develop custom web-based dashboards that reshape, filter and visualize data based on user behavior (e.g., <a href="https://613apps.ca/cgc" target="_blank">Canada Grains Council Trade Data Online</a>, <a href="https://613apps.ca/covid19" target="_blank">Covid-19 cases in Canada</a>).</li>
    <li>Have developed and designed 50+ websites for clients since 2006.</li>
  </ul>
</p>

<h3 class="roboto-black to-upper" style="border-bottom: 2px solid black;">Skills</h3>

<p class="roboto-black color-grey1">Modeling, Analysis and Visualization
  <br />
  <span class="roboto-light color-black">R, Python, OpenM++, C++, SQLite, Shiny, Quarto</span>
</p>

<p class="roboto-black color-grey1">Builds, Deployment and Pipelines
  <br />
  <span class="roboto-light color-black">Azure Data Factory, Azure Data Lake, Azure Databricks, Apache Spark, DigitalOcean droplets, Kubeflow, Kubernetes, Jupyter Notebook, Docker, Grafana</span>
</p>

<p class="roboto-black color-grey1">Stacks
  <br />
  <span class="roboto-light color-black">Debian, Ubuntu, Apache, Nginx, MySQL, MariaDB, PHP</span>
</p>

<p class="roboto-black color-grey1">Frontend
  <br />
  <span class="roboto-light color-black">HTML, CSS/SCSS, jQuery, JavaScript, DataTables, WordPress, React, Vue</span>
</p>

<h3 class="roboto-black to-upper" style="border-bottom: 2px solid black;">Education</h3>

<h4 class="roboto-light color-grey1" style="margin-top: 0; margin-bottom: 0; padding-top: 0; font-size: 1em;">MSc in Kinesiology</h4>

<p class="roboto-light color-black" style="margin-bottom: 0;">
  <span class="roboto-bold">University of Saskatchewan</span>
  <br />
  <span class="roboto-light color-grey1">{{< fa location-dot >}}</span>
  Saskatoon, Canada
</p>